import { spawn } from 'node:child_process';
import path from 'node:path';
import type { Harness, Settings, Task } from '../shared/types';
import { DEFAULT_SHELL, codexPermissionArgs, resolveEnvironment, resolveHarness } from '../shared/environments';
import type { HostKind } from './host';
import { wslDistroName } from './host';
import type { Logger } from './log';
import { createTarget, type Target } from './target';
import { writeText } from './store/fsutil';

/**
 * The harness command line as a run would build it — model, permission mode,
 * harness args, extra args — minus the prompt and the run plumbing (system
 * prompt, settings, headless flags): a plain interactive session for the user.
 */
export function terminalHarnessCommand(task: Task, target: Target, harness: Harness): string {
  const q = (s: string) => target.quote(s);
  const a = task.agent;
  const parts: string[] = [harness.command];
  if (harness.kind === 'claude-code') {
    if (a.model) parts.push('--model', q(a.model));
    if (a.permissionMode) parts.push('--permission-mode', q(a.permissionMode));
  } else if (harness.kind === 'codex') {
    for (const arg of codexPermissionArgs(a.permissionMode, true)) parts.push(arg);
    if (a.model) parts.push('--model', q(a.model));
  }
  for (const arg of harness.args) parts.push(q(arg));
  for (const extra of a.extraArgs) parts.push(q(extra));
  return parts.join(' ');
}

/** Launcher script for a terminal session: the run launcher's env + cd, without the run-only plumbing. */
export function renderTerminalScript(
  target: Target,
  task: Task,
  env: Record<string, string>,
  command: string,
): string {
  if (target.kind === 'windows') {
    const lines: string[] = [`# generated by looper — task ${task.id} terminal session`];
    for (const [k, v] of Object.entries(env)) lines.push(`$env:${k} = ${target.quote(v)}`);
    lines.push(`Set-Location -LiteralPath ${target.quote(task.cwd)}`);
    lines.push(command);
    lines.push('');
    return lines.join('\r\n');
  }
  const lines: string[] = ['#!/usr/bin/env bash', `# generated by looper — task ${task.id} terminal session`];
  for (const [k, v] of Object.entries(env)) lines.push(`export ${k}=${target.quote(v)}`);
  lines.push(`cd ${target.quote(task.cwd)} || echo "looper: cannot cd to ${task.cwd}" >&2`);
  // The sourcing shell is interactive, so a failing exec leaves it open with the error visible.
  lines.push('exec ' + command);
  lines.push('');
  return lines.join('\n');
}

export interface TerminalLaunch {
  command: string;
  args: string[];
  /** Windows host: the args are one pre-quoted cmd.exe line and must pass through verbatim. */
  verbatim?: boolean;
}

/** Quote one token of a cmd.exe `start` line. */
const winTok = (s: string) => (/[\s"']/.test(s) ? `"${s.replace(/"/g, '""')}"` : s);

export interface TerminalLaunchOpts {
  /** Launcher path as the target sees it. */
  launcherTarget: string;
  /** Host path of the launcher (mac/linux emulators run it directly). */
  launcherHost: string;
  /** `source '<launcherTarget>'`, quoted for the target shell (bash targets). */
  sourceCmd: string;
  /** Bash targets: the environment's shell + flags. Default: bash -lic. */
  shell?: string;
  /** WSL environments on a Windows host: the distro name. */
  distro?: string;
}

/**
 * Ways to open the launcher in a terminal window, in preference order. On
 * Windows `cmd /c start` hands the session to the user's default terminal
 * (Windows Terminal when set as default); from WSL the same line runs through
 * interop. On Linux the common emulators are tried until one spawns.
 */
export function buildTerminalLaunches(
  host: HostKind,
  targetKind: Target['kind'],
  opts: TerminalLaunchOpts,
): TerminalLaunch[] {
  if (targetKind === 'windows') {
    const ps = ['powershell.exe', '-NoExit', '-NoLogo', '-ExecutionPolicy', 'Bypass', '-File', opts.launcherTarget];
    if (host === 'windows') {
      return [{ command: 'cmd.exe', args: ['/d', '/c', `start "" ${ps.map(winTok).join(' ')}`], verbatim: true }];
    }
    return [{ command: 'cmd.exe', args: ['/c', 'start', '', ...ps] }];
  }
  const shellParts = (opts.shell?.trim() || DEFAULT_SHELL).split(/\s+/);
  const inner = [...shellParts, opts.sourceCmd];
  if (host === 'windows') {
    const line = ['wsl.exe', ...(opts.distro ? ['-d', opts.distro] : []), '--', ...inner];
    return [{ command: 'cmd.exe', args: ['/d', '/c', `start "" ${line.map(winTok).join(' ')}`], verbatim: true }];
  }
  if (host === 'wsl') {
    const distro = wslDistroName();
    return [
      { command: 'cmd.exe', args: ['/c', 'start', '', 'wsl.exe', ...(distro ? ['-d', distro] : []), '--', ...inner] },
    ];
  }
  if (host === 'mac') return [{ command: 'open', args: ['-a', 'Terminal', opts.launcherHost] }];
  const emulators = process.env.TERMINAL
    ? [process.env.TERMINAL]
    : ['x-terminal-emulator', 'gnome-terminal', 'konsole', 'xfce4-terminal', 'xterm'];
  return emulators.map((cmd) =>
    cmd === 'gnome-terminal' ? { command: cmd, args: ['--', ...inner] } : { command: cmd, args: ['-e', ...inner] },
  );
}

function trySpawn(l: TerminalLaunch): Promise<boolean> {
  return new Promise((resolve) => {
    try {
      const child = spawn(l.command, l.args, {
        detached: true,
        stdio: 'ignore',
        ...(l.verbatim ? { windowsVerbatimArguments: true } : {}),
      });
      child.once('error', () => resolve(false));
      child.once('spawn', () => {
        child.unref();
        resolve(true);
      });
    } catch {
      resolve(false);
    }
  });
}

export interface OpenTerminalDeps {
  host: HostKind;
  settings: Settings;
  /** Host directory to write the launcher into (the task's data dir). */
  taskDir: string;
  log: Logger;
}

/**
 * Open the task's harness in a terminal window: same environment, working
 * directory, model and arguments as a run, but interactive and prompt-less.
 */
export async function openTaskTerminal(task: Task, deps: OpenTerminalDeps): Promise<void> {
  const env = resolveEnvironment(task, deps.settings);
  const harness = resolveHarness(task, env);
  const target = createTarget(task, { host: deps.host, settings: deps.settings });
  const command = terminalHarnessCommand(task, target, harness);
  const launcherHost = path.join(deps.taskDir, 'terminal' + target.launcherExt);
  writeText(launcherHost, renderTerminalScript(target, task, { ...harness.env, ...task.env }, command), 0o755);
  const launcherTarget = target.toTargetPath(launcherHost);
  const launches = buildTerminalLaunches(deps.host, target.kind, {
    launcherTarget,
    launcherHost,
    sourceCmd: `source ${target.quote(launcherTarget)}`,
    shell: env.kind !== 'windows' ? env.shell : undefined,
    distro: env.kind === 'wsl' ? env.distro : undefined,
  });
  for (const l of launches) {
    if (await trySpawn(l)) {
      deps.log.info(`[${task.id}] opened terminal: ${l.command} ${l.args.join(' ')}`);
      return;
    }
  }
  throw new Error('Could not open a terminal window.');
}
